spring:
  application:
    name: upload-service

  # Spring Cloud Config ????
  cloud:
    config:
      enabled: false

  # ?????? ??
  datasource:
    url: jdbc:mariadb://localhost:3306/uploaddb?serverTimezone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: vmware1!

  # JPA ??
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # H2 ?? ??
  h2:
    console:
      enabled: true
      path: /h2-console

  # RabbitMQ ??
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  # ?? ??? ??
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

# ?? ??
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

# ?? ?? ?? ??
file:
  upload-dir: ./uploads/temp

# ?? ??
logging:
  level:
    root: INFO
    com.example: DEBUG
    org.springframework.amqp: INFO

# ????? ??
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

---
# Docker ??? ??
spring:
  config:
    activate:
      on-profile: docker

  # Docker ??? RabbitMQ ??
  rabbitmq:
    host: rabbitmq
    port: 5672

# Docker ??? ?? ?? ??
file:
  upload-dir: /app/uploads/temp