server:
  port: 8083

spring:
  application:
    name: validation-service

  # Spring Cloud Config ????
  cloud:
    config:
      enabled: false

  # RabbitMQ ??
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
          multiplier: 2.0

# ?? ??
logging:
  level:
    root: INFO
    com.example: DEBUG
    org.springframework.amqp: INFO

# ????? ??
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

---
# Docker ??? ??
spring:
  config:
    activate:
      on-profile: docker

  # RabbitMQ ??
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 5000
          max-attempts: 3
          multiplier: 2.0

  # ?? ??? ??
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# MinIO ??
minio:
  endpoint: ${MINIO_ENDPOINT:http://minio:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  bucket-name: ${MINIO_BUCKET_NAME:content-pipeline}
  temp-bucket-name: ${MINIO_TEMP_BUCKET_NAME:temp-uploads}
  presigned-url-expiry: 7

# ??? ??
app:
  upload:
    temp-dir: /app/uploads/temp